
#' Generate ARMA Time Series Data
#'
#' Simulates a time series from an ARMA(p, q) process for teaching and experimentation.
#' The function generates data by recursively applying autoregressive (AR) and
#' moving average (MA) components to a sequence of innovations (random shocks).
#'
#' This is a simple implementation intended for educational purposes, illustrating
#' how AR and MA components combine to produce temporal dependence.
#'
#' @param n Integer. Length of the time series to generate.
#' @param ar Numeric vector of autoregressive coefficients (\eqn{\phi_1, \ldots, \phi_p}).
#' Default is 0 (no AR component).
#' @param ma Numeric vector of moving average coefficients (\eqn{\theta_1, \ldots, \theta_q}).
#' Default is 0 (no MA component).
#' @param gen Function used to generate innovations (random shocks).
#' Default is \code{rnorm}. Must accept argument \code{n}.
#' @param ... Additional arguments passed to \code{gen} (e.g. \code{mean}, \code{sd}).
#'
#' @details
#' The generated process follows the form:
#' \deqn{
#'   X_t = \sum_{i=1}^p \phi_i X_{t-i} + Z_t + \sum_{j=1}^q \theta_j Z_{t-j}
#' }
#' where \eqn{Z_t} are independent innovations generated by \code{gen}.
#'
#' The function initializes past values with zeros and generates additional
#' innovations to account for the MA(q) component.
#'
#' Note that this implementation does not check for stationarity or invertibility.
#' Users should ensure that the chosen coefficients lead to a well-defined process.
#'
#' @return A univariate time series object of class \code{ts}.
#'
#' @examples
#' # AR(1) process
#' x <- arma_gen(n = 100, ar = 0.7)
#' plot(x)
#'
#' # MA(1) process
#' x <- arma_gen(n = 100, ma = 0.5)
#' plot(x)
#'
#' # ARMA(1,1) process
#' x <- arma_gen(n = 100, ar = 0.7, ma = -0.4)
#' plot(x)
#'
#' # Using non-Gaussian innovations
#' x <- arma_gen(n = 100, ar = 0.5, gen = runif, min = -1, max = 1)
#' plot(x)
#'
#' @seealso \code{\link{arima.sim}}
#'
#' @export
arma_gen <- function(n,
                     ar = 0,
                     ma = 0,
                     gen = rnorm,
                     ...) {
  p <- length(ar)
  q <- length(ma)
  inno <- gen(n + q, ...)
  out <- vector("numeric", length = n + p)
  if (p > 0)
    out[1:p] <- 0
  for (t in 1:n) {
    out[t + p] <- inno[t + q]
    if (p > 0)
      out[t + p] <- out[t + p] + sum(ar * out[(t + p - 1):t])
    if (q > 0)
      out[t + p] <- out[t + p] + sum(ma * inno[(t + q - 1):t])
  }
  if (p > 0)
    out <- out[-(1:p)]
  as.ts(out)
}

#' Visualize ARMA Time Series and Their Correlation Structure
#'
#' Simulates an ARMA(p, q) time series and displays key diagnostic plots:
#' the full series, a zoomed-in segment, and the corresponding autocorrelation
#' (ACF) and partial autocorrelation (PACF) functions.
#'
#' This function is designed for teaching, helping students connect model
#' parameters to observable patterns in time series and their correlation
#' structure.
#'
#' @param n Integer. Length of the time series to generate (default: 5000).
#' @param ar Numeric vector of autoregressive coefficients. Default is empty
#' (no AR component).
#' @param ma Numeric vector of moving average coefficients. Default is empty
#' (no MA component).
#' @param gen Function used to generate innovations (random shocks).
#' Default is \code{rnorm}.
#' @param lag.max Integer. Maximum lag for ACF and PACF plots (default: 40).
#'
#' @details
#' The function generates a time series using \code{\link{arma_gen}} and produces
#' four plots:
#'
#' \itemize{
#'   \item The full simulated time series
#'   \item A zoomed-in view (first \eqn{\sqrt{n}} observations)
#'   \item The autocorrelation function (ACF)
#'   \item The partial autocorrelation function (PACF)
#' }
#'
#' This allows direct comparison between:
#' \itemize{
#'   \item AR processes (typically show slowly decaying ACF and truncated PACF)
#'   \item MA processes (typically show truncated ACF and decaying PACF)
#'   \item ARMA processes (mixed behavior)
#' }
#'
#' The function is intended for exploratory use and classroom demonstrations.
#'
#' @return Invisibly returns the simulated time series (object of class \code{ts}).
#'
#' @examples
#' # AR(1) example
#' arma_plot(n = 1000, ar = 0.7)
#'
#' # MA(1) example
#' arma_plot(n = 1000, ma = 0.5)
#'
#' # ARMA(1,1) example
#' arma_plot(n = 1000, ar = 0.7, ma = -0.4)
#'
#' # Compare positive and negative AR coefficients
#' arma_plot(n = 1000, ar = 0.8)
#' arma_plot(n = 1000, ar = -0.8)
#'
#' @seealso \code{\link{arma_gen}}, \code{\link{acf}}, \code{\link{pacf}}
#'
#' @export
arma_plot <- function(n = 5000,
                      ar = numeric(0),
                      ma = numeric(0),
                      gen = rnorm,
                      lag.max = 40) {
  x <- arma_gen(n = n,
                ar = ar,
                ma = ma,
                gen = gen)
  par(mfrow = c(2, 2), oma = c(0, 0, 0, 0))
  par(mar = c(3, 4, 2, 0) + 0.1)
  plot(
    x,
    lwd = 2,
    main = paste("AR(", length(ar), ")/MA(", length(ma), ")", sep = ""),
    ylab = "X"
  )
  plot(
    x[0:floor(sqrt(n))],
    type = "l",
    lwd = 2,
    main = "Zoom",
    ylab = "X"
  )
  par(mar = c(3, 4, 0, 0) + 0.1)
  acf(x,
      lwd = 6,
      lag.max = lag.max,
      ylim = c(-1, 1))
  pacf(x,
       lwd = 6,
       lag.max = lag.max,
       ylim = c(-1, 1))
}

#' Distribute a Total Value Across Lags
#'
#' Creates a vector of equal values that sum to a specified total.
#' Useful for constructing AR or MA coefficient vectors where the
#' total influence is fixed but distributed across multiple lags.
#'
#' @param total Numeric. Total value to distribute.
#' @param length Integer. Number of elements (lags).
#'
#' @return Numeric vector of length \code{length}, where each element
#' equals \code{total / length}.
#'
#' @details
#' This function is useful for teaching how the distribution of
#' coefficients across lags affects the behavior of AR and MA processes.
#'
#' @examples
#' spread(0.9, length = 3)
#' # c(0.3, 0.3, 0.3)
#'
#' # Use in AR models
#' arma_plot(ar = spread(0.9, length = 5))
#'
#' @export
spread <- function(total, length=1) rep(total / length, length)
